apiVersion: v1
kind: Pod
metadata:
  name: fendpod
  labels:
    app: greet
    baxter: frontend
spec:
  containers:
    - name: exkubecont
      image: exkubedemo:v1
      ports:
        - containerPort: 8082