apiVersion: v1
kind: Service
metadata:
  name: fendsvc
  labels:
    app: greet
    baxter: frontend
spec:
  type: NodePort
  ports:
    - port: 8082
  selector:
    app: greet
    baxter: frontend