apiVersion: v1
kind: Service
metadata:
  name: bendsvc
  labels:
    app: greet
    baxter: backend
spec:
  type: ClusterIP
  ports: 
    - port: 3306
  selector:
    app: greet
    baxter: backend
